[package]
name = "hrt"
version = "0.1.0"
authors = ["Beatrix Klebe <bklebe@users.noreply.github.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
chrono-tz = "0.5"
timeago = "0.1"
fs_extra = "1.1.0"
dirs = "1.0"